version: '3.7'

services:

  api-express-typescript:
    build:
      context: .
      dockerfile: ./.docker/config/Dockerfile
    entrypoint: ./.docker/entrypoint.sh
    container_name: api-express-typescript
    tty: true
    ports:
      - 3333:3333
      - 3000:3000
    environment:
      PORT: 3000
      MONGO_URI: mongodb+srv://dbAdmin:12345@tsnode.fog8d.mongodb.net/tallos_rd?retryWrites=true&w=majority
      KEY_TOKEN: senhaApiTeste
    volumes:
      - .:/usr/api-express-typescript/app
