version: '3.1'

services:

  app:
    build: .
    restart: always
    container_name: teste-tallos
    entrypoint: sh ./.docker/entrypoint.sh
    volumes:
      - ./:/usr/app
    ports:
      - 3000:3333

  db:
    build: ./src/data/
    restart: always
    environment:
      POSTGRES_PASSWORD: teste
      POSTGRES_USER: teste
    volumes:
    - ./src/data:/usr/app

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080